// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwSxi6qRHStZyyTD0G_AVlZg76GxQtJ30',
    appId: '1:934981189341:web:c38716027a0af3a38da534',
    messagingSenderId: '934981189341',
    projectId: 'integrador-bd',
    authDomain: 'integrador-bd.firebaseapp.com',
    databaseURL: 'https://integrador-bd-default-rtdb.firebaseio.com',
    storageBucket: 'integrador-bd.firebasestorage.app',
    measurementId: 'G-ZM870MCEYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnrOkD-wvuc_Nt9R1qSTlCwgSOPh4W7wM',
    appId: '1:934981189341:android:835baecc0282de608da534',
    messagingSenderId: '934981189341',
    projectId: 'integrador-bd',
    databaseURL: 'https://integrador-bd-default-rtdb.firebaseio.com',
    storageBucket: 'integrador-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVqD_jdrT42TiODVOvH5xs1oO4nju41Fc',
    appId: '1:934981189341:ios:810ed25221adfaf28da534',
    messagingSenderId: '934981189341',
    projectId: 'integrador-bd',
    databaseURL: 'https://integrador-bd-default-rtdb.firebaseio.com',
    storageBucket: 'integrador-bd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVqD_jdrT42TiODVOvH5xs1oO4nju41Fc',
    appId: '1:934981189341:ios:810ed25221adfaf28da534',
    messagingSenderId: '934981189341',
    projectId: 'integrador-bd',
    databaseURL: 'https://integrador-bd-default-rtdb.firebaseio.com',
    storageBucket: 'integrador-bd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwSxi6qRHStZyyTD0G_AVlZg76GxQtJ30',
    appId: '1:934981189341:web:c6e081c712787c358da534',
    messagingSenderId: '934981189341',
    projectId: 'integrador-bd',
    authDomain: 'integrador-bd.firebaseapp.com',
    databaseURL: 'https://integrador-bd-default-rtdb.firebaseio.com',
    storageBucket: 'integrador-bd.firebasestorage.app',
    measurementId: 'G-7M32JT2GYJ',
  );
}
